### ISSUE TITLE
savewords broken by removed critters

### ISSUE THREAD

**Issue by XinacS** [Nuku/Flexible-Survival#1465]
Over at the flexible survival blog someone noticed that the safeword cannot be applied because of a non existent entry in the critters table.
I guess it is because some of them had to be removed to get around the current compiler issues. Maybe a dummy line could be added to the table to make the safewords work again.

**Comment by TigerStripes** [comment]
No creatures have been removed as of yet.  That said, inventory might be a
little messed up, as some quest-type items from that content may no longer
exist.

**Comment by XinacS** [comment]
Alright, I didn't check it out myself. :)
The error message he posted made me think that:
*** Run-time problem P22: Attempt to look up a non-existent row in the table 'Table of random critters'.

**Comment by TigerStripes** [comment]
They might be doing something silly like planning in a game where some
content they need (from their saveword) is banned in their current game.
Other than that, nothing immediately comes to mind as a reason for this.

**Comment by XinacS** [comment]
Ah, didn't think of that. That indeed could be a reason if it blocks critters from being added to the table.
I guess this can be closed then. :)

**Comment by TigerStripes** [comment]
Well, what happens is the game adds every creature into the table when it
initialized.  Once the player goes through the start procedure, selects
their bans and starts to play, the game scrubs any banned creatures from
the table entirely.

**Comment by XinacS** [comment]
I see, thanks!

**Comment by TigerStripes** [comment]
If it persists, then something else is probably going on though.
