### ISSUE TITLE
Perk/Merit exclusions missing

### ISSUE THREAD

**Issue by ambjoorn94** [Nuku/Flexible-Survival#1537]
While perk **Egg Sack** excludes ***Sterile***, ***Internal Genitals***, ***Internal Testicles***, ***No Balls*** and ***Humble Balls***, none of the excluded exclude Egg Sack. Is this intentional or was it missed when adding them?

I also noticed that **Compatible Gender** is marked as a Vanity Perk, says that it requires 2 Vanity Perk Points, but when taking it, you use 2 normal perk points.

**Comment by TigerStripes** [comment]
I believe these deal with the multiplayer game.  This code repository is
for the single-player game.

**Comment by ambjoorn94** [comment]
Oh, my bad... Where do I post this for the multiplayer game?

**Comment by TigerStripes** [comment]
Try posting it here:
http://web.flexiblesurvival.com/viewforum.php?f=7
