### ISSUE TITLE
'bottle water' error

### ISSUE THREAD

**Issue by Strongbird** [Nuku/Flexible-Survival#1561]
In Scavevents, Tiger Den, and Main Storyline, the 'water bottle' item is listed as 'bottle water'.

This was brought to my attention when trying to turn in the supplies for Chase, the tiger. Talking to him with > 10 food and water never resulted in the dialogue to progress triggering. Please investigate and fix.

**Comment by TigerStripes** [comment]
You beat me to it.  I wrote the fix yesterday, but was saving it to go with
the update I'm finishing up tonight.

**Comment by Nuku** [comment]
I just closed it because you asked me to?

**Comment by TigerStripes** [comment]
Alright then.  I'll send my fix later today.
