### ISSUE TITLE
Flexible Infection story file lost without a commit message?

### ISSUE THREAD

**Issue by vmattwin** [Nuku/Flexible-Survival#1590]
The flexible infection subfolder disappeared between commits https://github.com/Nuku/Flexible-Survival/commit/cd9840a91a81dafcc51cb14d67c176173cff44ba and https://github.com/Nuku/Flexible-Survival/commit/8c5001ab31ceb0991dd1d4460b5358368f587837 yet its not in the commit history. 
If  you use "show repository at the time of this commit" you can see it disappear

**Comment by Nuku** [comment]
Odd
