### ISSUE TITLE
Online play, release 57, with Quixe requires extra enter after "look storage locker"

### ISSUE THREAD

**Issue by BroadcastGames** [Nuku/Flexible-Survival#1643]
Hello. I'm looking over the code as an example of a complex Inform 7 game. Thank you for open sourcing the work.

When I play online: http://www.scworlds.net/FI/play.html

I notice at the start if I do "look storage locker" it seems to not do anything on Quixe. I have to press [enter] key a second time before it shows output.  Is this a bug in the current build of the game, or in Quixe, etc? Or is this an intentional behavior to have to press [enter] after clicking on hyperlinks?  If I free-form type "look storage locker" it seems like a bug?

**Comment by Nuku** [comment]
Curious. Does it exhibit this outside of Quixe?

**Comment by BroadcastGames** [comment]
I just ran it from the Glulx interpreter inside Inform 7 6M62 off the latest Github checkout - and it has the same issue. So, this behavior isn't unique to Quixe and happens right in the Inform 7 IDE.

**Comment by Nuku** [comment]
Fixed.

**Comment by BroadcastGames** [comment]
Tested, confirmed fixed by commit c93df2767f98540d294da3c9530191fa878b5a71
