### ISSUE TITLE
Case sensitive filename problems for Figures causes problems with Inform 7 Release

### ISSUE THREAD

**Issue by BroadcastGames** [Nuku/Flexible-Survival#1644]
The Github source has filenames that are not precise matches. On Linux systems this causes a lot of problems with release builds reporting missing figures.

Example: https://github.com/Nuku/Flexible-Survival/blob/master/Core%20Mechanics/FS%20Graphics.i7x#L99

```
 Figure of BrutusEvil_icon is the file "Brutus_evil.jpg".
```

And the filename on Github is here: https://github.com/Nuku/Flexible-Survival/blob/master/Figures/Brutus_Evil.jpg

Notice the "E" in "Evil" is not the same for the Inform reference as it is in the disk files.

**Comment by Nuku** [comment]
If you want to patch those, that would be grand.

**Comment by BroadcastGames** [comment]
Can you help me out with a quick question? I'm still pretty new to Inform 7. When do the Figure images appear?  For example, I encountered Orthas and did "examine Orthas" from the online Quixe play - should this line invoke the jpg image?

      Figure of Orthas_icon is the file "orthas.jpg".

Is it an issue that Quixe doesn't show the images? Or can you give me walkthrough steps to show one of the images in the game play?

**Comment by Nuku** [comment]
quixe doesn't display images, I don't -think-?

**Comment by BroadcastGames** [comment]
Quixe does work with some extensions to play images, for example - this game Alabaster does show images on the left side of the screen: http://www.eblong.com/zarf/glulx/quixe/quixe/play-remote.html?story=http%3A%2F%2Fmirror.ifarchive.org%2Fif-archive%2Fgames%2Fglulx%2FAlabaster.gblorb&enter=Play+it%21

**Comment by Nuku** [comment]
Interesting. Do you know how?

**Comment by BroadcastGames** [comment]
I still have a lot to learn, but that's what I'm poking around it. Alabaster is  a poor example story, because it uses extensions that no longer compile with new Inform 7 releases.  I'm still trying to find examples that use images and complex layout like you have.

Counterfeit Monkey is now fully open source and builds on latest Inform 7: https://github.com/i7/counterfeit-monkey - and it uses complex graphics that work with online browser play (Quixe).  To show online play with graphics: http://eblong.com/zarf/glulx/quixe/quixe/play-remote.html?story=http%3A%2F%2Fmirror.ifarchive.org%2Fif-archive%2Fgames%2Fglulx%2FCounterfeitMonkey.gblorb&enter=Play+it%21  (It is slow, but not so much due to the graphics but due to the gameplay logic).

**Comment by Nuku** [comment]
That does not appear to include his libraries.

**Comment by BroadcastGames** [comment]
Here are the list of filenames that cause the Release to fail on case-sensitive file systems.  Instead of changing the code, these are the properly named files in the Figures directory:

	Brutus_evil.jpg
	Brutus_good.jpg
	FSTF_YuppieMink_ig.jpg
	Mammoth_ig.png
	SnowBat_ig.jpg
	beaver_ig1.jpg
	grant_ig2.jpg

**Comment by Nuku** [comment]
I tried renaming them on my system. Github doesn't see any changes...
