### ISSUE TITLE
Cock entry for shaft beast is far too verbose.

### ISSUE THREAD

**Issue by ElAcechador** [Nuku/Flexible-Survival#1669]
> Drawn to her by her sweet scent, you take Honey into your arms and run your hands over her body.  She buzzes happily and hugs you tightly.  Lifting her small body up into your arms, you slide your cock into her warm pussy.  Normally hidden under a puff of soft, golden hair, her honeypot is tight and wet around your **draconian shaped cock tip, as well as 8 small breasts along it's underside, proportional to the size of your tool, your manhood is also ridged along the sides and barbed all over the glans and edges, quite an interesting cock**.  Her wings buzz excitedly as she bounces in your arms, riding your cock until you finally pump your thick seed into her.

That's fine for character descriptions, but in places like this, it's just really out of place.

**Comment by Nuku** [comment]
Fixed! Not uploaded yet. Will do the next major revision.
