### ISSUE TITLE
`load game` command does not restore body types with spaces (or backticks) in the names.

### ISSUE THREAD

**Issue by dragontamer8740** [Nuku/Flexible-Survival#1807]
Typing `load game` (or doing `recite` and pasting in your savewords) does not not restore your character's body part types anymore. Whatever your body looks like in the currently running game is retained after 'loading' the game again from the save word.

If it matters the char in question has the "slutty dragoness" body type and I am playing in Gargoyle on a linux system. All the other save data is correctly loaded, and it was also correctly loaded in a very old version of the game I was playing until I re-downloaded recently. The "zag" interpreter does not work either.

"succubus" body types are restored, but "Slutty\`Dragoness" and "Herm\`Hyena" and "Parasitic\`Plant" types are not.

**Comment by executaball** [comment]
Hm that's weird. Right now we _do_ have handling for that:
![image](https://user-images.githubusercontent.com/18548573/33331729-57e7b3f2-d49d-11e7-9cd4-9baeb0714baa.png)
can you send over your entire saveword?

**Comment by dragontamer8740** [comment]
@FoxyDysphoria This is still not fixed. Just started a new game. Not sure why you're marking it closed.
txsave:
```
* //4DA761E4-4441-4313-BEDE-B3A78D3DABAA// txsave
17}12}12}12}12}12}0}29}100}-39}0}Slutty`Dragoness}Slutty`Dragoness}Slutty`Dragoness}Slutty`Dragoness}Slutty`Dragoness}5}0}1}2}0}0}6}4}0}0}journal}0}0}0}171214_223}nothing}0}0}0}0}0}0}0}0}0}000100B}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0
```
txsave2:
```
* //4DA761E4-4441-4313-BEDE-B3A78D3DABAA// txsave2
chantpartA}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0000000000000N}0}0}0}0}0}0}0}0}64}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}100}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}2}0}0
```
txsave3:
```
* //4DA761E4-4441-4313-BEDE-B3A78D3DABAA// txsave3
chantpartB}0}0}0}0000000000000B}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}AAAAAAAAAAAA}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0}0
```

**Comment by dragontamer8740** [comment]
@executaball ping.

**Comment by FoxyDysphoria** [comment]
@dragontamer8740 I marked it as closed as we hadn't heard back from you. Sorry about that. 

Now, regarding that save, I don't actually know why there's tilde's in there. I haven't worked with saveword myself, but I can look into it to see.

@executaball What are your thoughts on this?

**Comment by dragontamer8740** [comment]
Happens with spaces or backticks. Backticks is just how the game saves them.
I think it's trying to match the names with spaces to the [list of all critters] and failing, probably for similar reasons to unsanitized database inputs.

This is just a guess, I'm a C programmer at heart and Inform 7 is so different that it confuses me :\

**Comment by dragontamer8740** [comment]
@FoxyDysphoria Shall I open a new issue? Or can this one be re-opened?
