### ISSUE TITLE
Quixe run: gli_put_char: window has pending line request error, Online version

### ISSUE THREAD

**Issue by Valareos** [Nuku/Flexible-Survival#1824]
Though probably reproduce using other methods, I can verify this happens each time in this chain of events

1, start new game
2. Gender: Female
3. Gender Lock: Cunt Boy, start as lock
4. Go up out of bunker
5. Use Trixie Cheat Code
6. Turn on Unerring Hunter
7. Hunt Beach
8. West, then Down, then south, then east to WIld Fringe
9 Hunt shark warrior
10. Agree to reward him
11. Ride him or suck him off gives same error.

The same thing occurs selecting all default settings, not turning on the unerring hunter cheat, and doing it though the regular hunt commands

**Comment by FoxyDysphoria** [comment]
A lot of this stuff isn't easy for us to fix / troubleshoot, as the web version tends to bug out fairly often. If possible, using the downloadable .gblorb file is the best way to play, as this eliminates any possible issues that your browser could cause.

Any chance you could give that a try and let us know if that fixes things?

**Comment by Valareos** [comment]
I certainly can. Give me a moment

**Comment by Valareos** [comment]
While waiting for it to  download, I have notice some issues already

`			if cocks of player > 0:
				say "     Do you want to [link]suck him off (0)[as]1[end link], [link]fuck him (1)[as]2[end link] or [link]ride him(2)[as]2[end link]?";`

correct me if I am wrong, but the fuck him link shows the same linking number as the ride him link, both as 2.

**Comment by Valareos** [comment]
also, the suck him should be as 0, fuck him as 1, and ride him as 2. 

otherwise, dont get the error on downloaded one

**Comment by FoxyDysphoria** [comment]
Yep, that's an issue. I'll reach out to Lone_Wanderer about that and try to
get a patch out!

**Comment by Valareos** [comment]
Im not entirely sure how the interpreter works for the online one, it may be hanging up on having multiple choices there. Ill retest it once that patch is done

**Comment by FoxyDysphoria** [comment]
A pull request (#1825) has been opened with a bugfix for the menu.

**Comment by Valareos** [comment]
I have done more trouble shooting for you on this issue. (still exists after the fix)

If you enter the number of the choice via the keyboard, it works just fine. If you click the link, it fails out.

The error most likely relates to the code

`while calcnumber < 0 or calcnumber > 2:
					say "Choice? (0-2)>";
					get a number;
				if calcnumber is 0:
					say "[tsw_oral]";
				else if calcnumber is 1:
					say "[tsw_fuck]";
				else:
					say "[tsw_ride]";`

Now, I am not used to this sort of programming (more of a php guy myself), but it seems that the system is not treating the link as a number for `get a number` to recognize.

**Comment by FoxyDysphoria** [comment]
`link as` just types whatever you link, automatically. This seems to be an issue with Quixie, so it's not something we can actually resolve, unfortunately. I honestly recommend using the desktop version, as it's faster and won't crash on ya. 

Sorry for the trouble!
