### ISSUE TITLE
Tanuki Shrine quest impossible to advance with female gender banned

### ISSUE THREAD

**Issue by ShylokVakarian** [Nuku/Flexible-Survival#1856]
The shrine 'nuki demanded batcubus milk, but I've banned both females and hermaphrodites.  I have been exploring the warehouse district for an hour or two, looking for an event that would give me it (like the event for finding the honeycomb for Elijah if you've banned females), but there is none, so it's now currently impossible for me to advance in the quest.

**Comment by Nuku** [comment]
I have an idea.

**Comment by ShylokVakarian** [comment]
Code it so each time it selects a new item, check to see if it's possible to obtain it and reselect if if can't?  If I could code, that's how I would do it.

**Comment by Nuku** [comment]
It cannot reliably determine if the item can be selected.

**Comment by Nuku** [comment]
Uploading a fix right now.
