### ISSUE TITLE
Blue Gryphon Herm player locked out of catching Icarus

### ISSUE THREAD

**Issue by mcneil-ryan-m** [Nuku/Flexible-Survival#2110]
Because the blue gryphon herm's parts aren't classified as feline or avian, players infected that way are locked out of catching Icarus in the zoo.

**Comment by Stadler76** [comment]
This has been fixed in the [May FS Update](https://github.com/Nuku/Flexible-Survival/commit/10d76c9f2dfe30f17e407793d3b40e3c7fa81514#diff-00fafdbd37f7c0ba17020cbc4d32d53d). At least I can now catch him as a blue gryphon herm, so I guess, this can be closed?

**Comment by Stadler76** [comment]
This has been fixed in the [May FS Update](https://github.com/Nuku/Flexible-Survival/commit/10d76c9f2dfe30f17e407793d3b40e3c7fa81514#diff-00fafdbd37f7c0ba17020cbc4d32d53d). At least I can now catch him as a blue gryphon herm, so I guess this can be closed?
