### ISSUE TITLE
Dragovixentaur's (and probably dragontaur's) can't fly

### ISSUE THREAD

**Issue by Stadler76** [Nuku/Flexible-Survival#2125]
I'm currently a dracovixentaur and for some reason I can't fly up to 'The Clouds' from the 'Campus Belltower'. I guess, the same applies to dragontaur's as well.

After a brief scan of the code, it seems, that the `FlightList` in [Inform/story.ni](https://github.com/Nuku/Flexible-Survival/blob/master/Inform/story.ni) isn't used anymore and instead has to be added to each infection file as
```i7
	add "Dracovixentaur" to the infections of FlightList;
```
and `Stripes/Dracovixentaur.i7x` and `Stripes/Dragontaur.i7x` both are missing that line.

**Comment by Stadler76** [comment]
Ok, this seems to be messed up even worse:
Entering `TagListReadout` in debug mode gives me:
FlightList: Bald Eagle, Batcubus, Bird of Paradise, Black Wasp, Blue Chaffinch, Blue Gryphon Herm, Butterfly, City Sprite, Corota, Drone Wasp, Fluffy Owl, Fruit Bat, Gargoyle, Harpy, Hawkman Female, Hawkman Male, Imp Male, Mothgirl, Pegasus, Queen Bee, Scarab Beetle, Seraphim Warrior, Siren, Snow Bat, Succubus, Sugar Glider and Wyvern

**Comment by Wahn128** [comment]
What exactly are you trying to say in your last comment?

**Comment by Stadler76** [comment]
Taking the list from Inform/story.ni:
```inform7
add { "Bald Eagle", "Bird of Paradise", "Black Wasp", "Butterfly", "Dragontaur", "Dracovixentaur", "Drone Wasp", "Ebonflame Whelp", "Ebonflame Dragator", "Ebonflame drake", "Fire Sprite", "Fluffy Owl", "Fruit Bat", "Hawkman Male", "Harpy", "Blue Gryphon Herm", "Mothgirl", "Pegasus", "Queen Bee", "Reindeer", "Snow Bat", "Vulpogryph", "Yamato Dragon", "Yamato Dragoness", "Wyvern" } to infections of FlightList;
```
There are some of them missing in the ingame list posted above.

Actually:
* Dracovixentaur
* Dragontaur
* Ebonflame Dragator
* Ebonflame drake
* Ebonflame Whelp
* Fire Sprite
* Vulpogryph
* Yamato Dragon
* Yamato Dragoness

So these need to be added to the `FlightList` in their corresponding files.

**Comment by Nuku** [comment]
Go ahead.

**Comment by Stadler76** [comment]
> Go ahead.

BTDT
