### ISSUE TITLE
Resolution of 'Spreading Flowers' is never set to 3.

### ISSUE THREAD

**Issue by crealname** [Nuku/Flexible-Survival#2261]
I looked into Joanna's file and it says that Spreading Flowers has to be at stage 3 to trigger the next step, however I see nothing after the flesh blob encounter which triggers this.

Discovered on Release 67 / Serial Number 200516 / Inform 7 build 6M62 (I6/v.6.33 lib 6/12N) D
Running the game on Fabularium for Android

EDIT: Renamed the report as dragontamer8740 pointed out a better one.

**Comment by dragontamer8740** [comment]
I'd just like to affirm that this is an oversight. I'd suggest renaming the issue to "resolution of 'Spreading Flowers' is never set to 3". Because that's the "root" of the issue, no pun intended.

**Comment by crealname** [comment]
Well this seems to have been fixed, I'm going to close it.
