### ISSUE TITLE
Attempting to start with mode 'Caught Outside' results in an error

### ISSUE THREAD

**Issue by crealname** [Nuku/Flexible-Survival#2295]
Details: 
- Downloaded latest version of Flexible Survival's installer today
- Playing through Windows Git on Windows 10 Home

If I attempt to start a game with Caught Outside, here's the result:

`*** Run-time problem P23: Attempt to look up a non-existent entry at column 31, row 254 of the table 'Table of Random Critters'.

*** Value handling failed: copy from null value ***`

If you require further info feel free to comment and I'll get back to you when I can.

![git_hthfh4b7pL](https://user-images.githubusercontent.com/67677691/95941003-f320bb80-0d9c-11eb-9f9d-2b3f8e3a1ae0.png)

**Comment by Nuku** [comment]
Is this sometimes? Every time?

**Comment by crealname** [comment]
Yes, it seems to be every time I try to start it that way. Oh, and I didn't install it in program files.

**Comment by crealname** [comment]
Do let me know if I can provide you with additional information.

**Comment by Wahn128** [comment]
This is resolved now.
