### ISSUE TITLE
Issue with Art Collector fight in Slut Rat Quest

### ISSUE THREAD

**Issue by DLDracoRex** [Nuku/Flexible-Survival#2297]
During the event "Art Collector" (part of the Slut Rat Quest found at https://github.com/Nuku/Flexible-Survival/blob/master/Stripes/RodAndRonda.i7x ), when the enemy "Leopardman" (the art collector) is defeated, the number "artleopardfight" remains at 3, which is meant to indicate that the player fled. As such, the event and thus the entire quest can not be completed.

**Comment by Wahn128** [comment]
This should be resolved now.
