### ISSUE TITLE
Hunt command broken when searching with multiple keywords

### ISSUE THREAD

**Issue by crealname** [Nuku/Flexible-Survival#2399]
**Using Offline raw files for 09/14/21**

Steps to reproduce:
- Start a new game
- Grab the chips and soda from various locations in the Grey Abbey Library
- Hunt "`Stabled Situation`" 2x
- Choose _Yes_ when prompted to request entry
- Hunt "`transformationledger`" and tear a page off when prompted
- Speak to Fancy about the token
- Nav/Hunt for Red Light District
- Hunt "`Kink Warehouse`"

Any time I try to search for it, I am met with "`Perhaps you should try looking somewhere closer to what you seek...`"

Now, if I'm not mistaken this was how I made my way to the warehouse in previous versions of the game, but at this point I'm unable to get there. I can replicate this issue on two devices thus far:
- Samsung Galaxy Tab S6 Lite using Fabularium from Google Play
- Windows 10 Home (Custom built PC) using Windows Git

Thank you for reading

P.S. I've edited this post multiple times, and I must add that I am not very experienced with posting on Github. If there's anything I could be doing better, feel free to suggest it to me.

**Comment by crealname** [comment]
Update: I am changing the title as I cannot hunt for any event in the Red Light District.

**Comment by crealname** [comment]
Update: It seems as though searching for anything with multiple words causes it to be unfindable, either "perhaps you should look closer" or "you don't think you can find anything like that here"

**Comment by crealname** [comment]
Hunting creatures seems to be fine however things like "hunt Pediatrics Lobby" cannot be found unless I do something like "hunt lobby"

**Comment by Wahn128** [comment]
You're simply not hunting in the right location, I think. Note that the fast travel room leading into each zone belongs to the "Outside" zone. Please take a step north into the actual red light district and try hunting there.

**Comment by crealname** [comment]
Ah, my bad. That wasn't a problem for me in previous versions I guess. No issue here then.
