### ISSUE TITLE
changes in Basic Functions.i7x preventing compiling

### ISSUE THREAD

**Issue by oblende** [Nuku/Flexible-Survival#2491]
Changes made in 'Basic Functions.i7x' in 'Core Mechanics' is preventing compilation of source text. I corrected the basic syntax errors in the choices rule that was preventing compilation, but compilation attempts fail with unknown error. I will admit that I am using a nonstandard by setup using wine to run the recommended beta 4 version of Inform, but this worked in previous attempts to compile before the recent changes in 'Basic Functions.i7x'.

Please note that I have not made any changes beyond correcting syntax errors. By all rights this should have compiled.

**Comment by Nuku** [comment]
Are you using the right version of inform? The game is so large it won't compile without.

**Comment by oblende** [comment]
I haven't tried the beta 5 yet, so it is possible that this could be the problem. Originally I had tried the latest release of Inform, but apparently they broke the language. There was lots of things that wouldn't work any more, so I had strictly followed the directions and tried to use the beta 4 build. So I guess the directions for building need to be updated.
