### ISSUE TITLE
Can't compile with beta 5

### ISSUE THREAD

**Issue by oblende** [Nuku/Flexible-Survival#2618]
Is there anything special, or a special modification that I need to do to the Inform compiler to get the current code on github to compile? I've adjusted the values related to code 10 compiler failures to what I think are unreasonably high values and I still can't get it to compile. Sure I'm running Inform on Linux using Wine, but it should still work just fine.

You should find attached a text file that contains the failure message.

[compile_failure.txt](https://github.com/Nuku/Flexible-Survival/files/12208572/compile_failure.txt)

**Comment by Nuku** [comment]
You need a different ni.exe.
https://drive.google.com/file/d/0BxUh1iVHP4kiM3JjTF8za2V0TG8/view?usp=drive_link&resourcekey=0-w-WjyPGZebqgvv8Zp8hf2g
